#!/usr/bin/env bash
# Distributes this repo's skills and hooks into every repo in orchestration/repos.json.
#
# One source of truth (fpl-orchestrator/skills/), reached everywhere by symlink, so editing a
# skill once changes what every session in every repo loads. Symlinks and the generated
# settings.json are MACHINE-LOCAL and gitignored — a fresh clone runs this script once.
# Idempotent: safe to re-run any time.
set -euo pipefail

ORCH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAN="$ORCH/orchestration/repos.json"
command -v jq >/dev/null || { echo "jq required"; exit 1; }

link_skills_into() {
  local repo="$1" name; name=$(basename "$repo")
  mkdir -p "$repo/.claude/skills"

  # Drop links we previously made that no longer have a source (renamed or removed skills).
  find "$repo/.claude/skills" -maxdepth 1 -type l | while read -r l; do
    [ -e "$l" ] || { rm -f "$l"; echo "  pruned dangling $(basename "$l")"; }
  done

  local n=0
  for kind in agent user; do
    for dir in "$ORCH/skills/$kind"/*/; do
      [ -d "$dir" ] || continue
      local skill; skill=$(basename "$dir")
      local target="$repo/.claude/skills/$skill"
      if [ -e "$target" ] && [ ! -L "$target" ]; then
        echo "  SKIP $skill — a real directory exists at $target (not overwriting)"; continue
      fi
      ln -sfn "${dir%/}" "$target"
      n=$((n+1))
    done
  done
  echo "  $name: $n skills linked"
}

write_settings() {
  local repo="$1" H="$ORCH/plugins/fpl/hooks" f="$1/.claude/settings.json"
  mkdir -p "$repo/.claude"
  # Merge into whatever is already there rather than clobbering local permissions.
  local existing='{}'; [ -f "$f" ] && existing=$(cat "$f")
  printf '%s' "$existing" | jq --arg h "$H" '
    .["$comment"] = "Generated by fpl-orchestrator/scripts/link-skills.sh. Hook paths are absolute because they point into the sibling orchestration repo. Machine-local: gitignored, re-run the script after a clone." |
    .hooks = {
      SessionStart: [{ hooks: [{ type:"command", command:("bash \"" + $h + "/session-brief.sh\""), timeout:10, statusMessage:"Reading gameweek state…" }] }],
      PreToolUse: [
        { matcher:"Edit|Write|MultiEdit", hooks:[{ type:"command", command:("bash \"" + $h + "/pre-edit-skill-router.sh\""), timeout:10 }] },
        { matcher:"Bash",                 hooks:[{ type:"command", command:("bash \"" + $h + "/pre-bash-guard.sh\""),        timeout:10 }] }
      ],
      PostToolUse: [
        { matcher:"Edit|Write|MultiEdit", hooks:[{ type:"command", command:("bash \"" + $h + "/post-edit-verify.sh\""), timeout:120, statusMessage:"Typechecking…" }] }
      ]
    }' > "$f.tmp" && mv "$f.tmp" "$f"
  echo "  $(basename "$repo"): hooks wired"
}

ensure_gitignore() {
  local repo="$1" gi="$1/.gitignore"
  grep -qxF '.claude/skills' "$gi" 2>/dev/null || printf '\n# generated by fpl-orchestrator/scripts/link-skills.sh (machine-local)\n.claude/skills\n.claude/settings.json\n.claude/settings.local.json\n' >> "$gi"
}

echo "Distributing skills + hooks from $ORCH"
jq -r '.repos[].path' "$MAN" | while read -r p; do
  repo="$(cd "$ORCH/$p" 2>/dev/null && pwd)" || { echo "  MISSING $p"; continue; }
  link_skills_into "$repo"
  # This repo keeps a COMMITTED .claude/settings.json using ${CLAUDE_PROJECT_DIR}; only the
  # siblings need absolute paths generated for them.
  if [ "$p" = "." ]; then echo "  fpl-orchestrator: hooks already committed (skipped)"; else
    write_settings "$repo"
    ensure_gitignore "$repo"
  fi
done

echo
echo "Done. Verify with: bash scripts/doctor.sh"
